title: Kolpinghaus Reutlingen
url: https://kolpinghaus-reutlingen.de
commit: 5e6e0156a1c2a8fff1e6216c3379aef343567410
image:
  url: https://res.cloudinary.com/kolpinghaus-rt/image/upload
  version: 1532618028
  option:
    default: c_lfill,g_auto,cs_srgb,q_auto
  max:
    w:
    h:

timezone: Europe/Berlin
future: true
excerpt_separator: <!--mehr-->

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  ignore:
    envs: ['development']
  blanklines: false
  profile: false

plugins:
   - jekyll-redirect-from


link: kolpinghaus-reutlingen.de

kontakt:
  city: 72764 Reutlingen
  street: Liststraße 26
  country: Deutschland
  phone: 07121 43340
  fax: 07121 43344
  email: info@kolpinghaus-reutlingen.de
  heimleiter: Hermann Rist
  hours:
    from: 8
    to: 17

author:
  name: Patrick Haußmann
  url:

google-site-verification:
  old: fWwRC4yG7LLptW6sN1izwv0Sy9kvKaOozazFVAYJafk
  new: tyvNJr99qMKWyfVYXxuD8ikqOpWjCQfdJv5WvywBGqE

collections:
  artikel:
    output: true
  veranstaltungen:
    output: true
  projekte:
    output: true

defaults:
  - scope:
      path: ""
      type: artikel
    values:
      layout: post
      active: artikel
      permalink: /artikel/:path/
      img:
        folder: artikel
  - scope:
      path: ""
      type: veranstaltungen
    values:
      layout: post
      active: veranstaltungen
      permalink: /veranstaltung/:path/
      img:
        folder: veranstaltungen
  - scope:
      path: ""
      type: projekte
    values:
      layout: post
      active: projekte
      permalink: /projekt/:path/
      img:
        folder: projekte
