title: Kolpinghaus Reutlingen
url: https://kolpinghaus-reutlingen.de
commit: 76a055c7d36306ddae49fbdf08ce0ee0445a8460
static:
  url: https://res.cloudinary.com/kolpinghaus-rt/image/upload/
  default: w_1920,h_1080,cs_srgb,f_auto,q_auto,c_limit
timezone: Europe/Berlin
future: true
excerpt_separator: <!--mehr-->

compress_html:
  clippings: []
  comments: ["<!-- ", " -->"]
  ignore:
    envs: ['development']
  blanklines: false
  profile: false

plugins:
   - jekyll-redirect-from


link: kolpinghaus-reutlingen.de

kontakt:
  city: 72764 Reutlingen
  street: Liststraße 26
  country: Deutschland
  phone: 07121 43340
  fax: 07121 43344
  email: info@kolpinghaus-reutlingen.de
  heimleiter: Hermann Rist
  hours:
    from: 8
    to: 17

author:
  name: Patrick Haußmann
  url:

google-site-verification:
  old: WKV36y8R6DIy6Q5bRY5m3UTQcTRnEZkPCvINlUtgSdc
  new: DAjMSM4ZZ3k1sZ4afGJMJ_GJELwRr8etG7cPkDtBmJw

collections:
  artikel:
    output: true
  veranstaltungen:
    output: true

defaults:
  - scope:
      path: ""
      type: artikel
    values:
      layout: post
      active: artikel
      permalink: /artikel/:path/
  - scope:
      path: ""
      type: veranstaltungen
    values:
      layout: post
      active: veranstaltungen
      permalink: /veranstaltung/:path/
